# Generated by Django 6.0.3 on 2026-04-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_address_patient_contact_patient_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='contact',
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
